@baseUrl = http://localhost:3000


# RECEITAS
###
GET {{baseUrl}}/receitas/
?limit=10
&offset=15
###
GET {{baseUrl}}/receitas/2
###
POST {{baseUrl}}/receitas/
Content-Type: application/json

{
    "receita": 5000,
    "origem": "Dividendos",
    "responsavel": "Ricardo"
}
###Atualiza
PATCH {{baseUrl}}/receitas/2
Content-Type: application/json

{
    "origem": "Pix"
}
###Apaga
DELETE  {{baseUrl}}/receitas/2




###AppControllerGetHello
# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

###ExemplodeRota
# @name ExemploDeRota
GET {{baseUrl}}/home/exemplo

###ConceitosManualController
# @name ConceitosManualControllerHome
GET {{baseUrl}}/conceitos-manual

###ConceitosAutomaticoController
# @name ConceitosAutomaticoControllerHome
GET {{baseUrl}}/conceitos-automatico
